name: proyecto
description: "Una aplicación de diagnóstico automotriz construida con Flutter y Clean Architecture."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  equatable: ^2.0.5
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.4
  intl: ^0.19.0
  flutter_animate: ^4.5.0

  cupertino_icons: ^1.0.2

  dio: ^5.4.3+1
  url_launcher: ^6.3.0

  # Para almacenar de forma segura el token de autenticación
  flutter_secure_storage: ^9.2.2

  # Para inyección de dependencias y service locator (muy útil)
  get_it: ^7.7.0
  lottie: ^2.7.0
  geolocator: ^14.0.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
